In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = np.random.randint(0,100,(10,2))

In [7]:
data

array([[64, 29],
       [36,  2],
       [ 3, 12],
       [87, 80],
       [40, 81],
       [77,  4],
       [46, 61],
       [72, 42],
       [ 6, 49],
       [93, 89]])

In [8]:
scaler_model = MinMaxScaler()

In [9]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [10]:
 scaler_model.fit(data)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

#### _Computes the minimum and maximum to be used for later scaling._

In [14]:
 scaler_model.transform(data)

array([[0.67777778, 0.31034483],
       [0.36666667, 0.        ],
       [0.        , 0.11494253],
       [0.93333333, 0.89655172],
       [0.41111111, 0.90804598],
       [0.82222222, 0.02298851],
       [0.47777778, 0.67816092],
       [0.76666667, 0.45977011],
       [0.03333333, 0.54022989],
       [1.        , 1.        ]])

#### _Scales features of X according to feature__range._

In [15]:
 scaler_model.fit_transform(data)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.67777778, 0.31034483],
       [0.36666667, 0.        ],
       [0.        , 0.11494253],
       [0.93333333, 0.89655172],
       [0.41111111, 0.90804598],
       [0.82222222, 0.02298851],
       [0.47777778, 0.67816092],
       [0.76666667, 0.45977011],
       [0.03333333, 0.54022989],
       [1.        , 1.        ]])

#### _Fits to data, then transforms it._

In [16]:
import pandas as pd

In [17]:
mydata = np.random.randint(0,101,(50,4))

In [18]:
mydata

array([[56, 93, 59, 61],
       [29, 15, 93, 84],
       [63, 69, 54,  2],
       [42, 29, 81,  3],
       [24, 15, 11, 43],
       [87, 14, 13, 61],
       [91,  7,  2, 49],
       [23, 63, 43, 16],
       [48, 80, 50,  6],
       [81, 67, 22,  1],
       [83, 60, 60, 23],
       [49, 22, 35, 72],
       [20, 62, 47, 63],
       [28, 43,  1, 61],
       [95, 51, 74, 60],
       [25, 15, 13, 37],
       [98, 36, 37, 28],
       [43, 53, 91, 35],
       [ 7,  6, 36,  0],
       [58, 56, 93, 17],
       [20, 76, 93, 20],
       [11, 84,  8,  2],
       [12, 44, 49, 70],
       [85, 70,  9, 23],
       [32, 27, 30, 93],
       [ 3, 55,  1, 20],
       [72, 20, 88, 19],
       [25, 22, 10, 11],
       [ 9,  2, 78, 18],
       [28, 42,  8, 16],
       [58, 81, 42, 21],
       [36, 76, 24, 65],
       [14, 37, 35, 18],
       [16, 70, 43, 95],
       [21,  5, 94,  0],
       [79, 36, 32, 45],
       [ 1, 61, 80, 48],
       [13, 22, 93, 78],
       [40, 45, 58,  1],
       [59, 14, 15, 46],


In [23]:
df = pd.DataFrame(data=mydata, columns=['f1','f2','f3','label'])

In [24]:
df

f1  f2  f3  label
0   56  93  59     61
1   29  15  93     84
2   63  69  54      2
3   42  29  81      3
4   24  15  11     43
5   87  14  13     61
6   91   7   2     49
7   23  63  43     16
8   48  80  50      6
9   81  67  22      1
10  83  60  60     23
11  49  22  35     72
12  20  62  47     63
13  28  43   1     61
14  95  51  74     60
15  25  15  13     37
16  98  36  37     28
17  43  53  91     35
18   7   6  36      0
19  58  56  93     17
20  20  76  93     20
21  11  84   8      2
22  12  44  49     70
23  85  70   9     23
24  32  27  30     93
25   3  55   1     20
26  72  20  88     19
27  25  22  10     11
28   9   2  78     18
29  28  42   8     16
30  58  81  42     21
31  36  76  24     65
32  14  37  35     18
33  16  70  43     95
34  21   5  94      0
35  79  36  32     45
36   1  61  80     48
37  13  22  93     78
38  40  45  58      1
39  59  14  15     46
40  34  93  37     74
41  66  42  27     17
42   5  33   6     91
43  23  84  60     99
44  69  25  95     93
45  25  90  87     73
46  10  20  17      9
47   2   5  98     90
48  10  52  74     25
49  98   2  45     11

In [33]:
X = df[['f1','f2','f3']]

In [34]:
y = df[['label']]

In [35]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [39]:
X_train.shape

(35, 3)

In [40]:
X_test.shape

(15, 3)