# TF Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
 print(result)

b'Hello World'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [14]:
print(result)

30


In [15]:
const = tf.constant(10)

In [16]:
fill_mat = tf.fill((4,4),10)

In [17]:
myzeros = tf.zeros((4,4))

In [18]:
myones = tf.ones((4,4))

In [19]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [20]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [21]:
type(myzeros)

tensorflow.python.framework.ops.Tensor

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [23]:
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-3.7903956e-01  2.0839792e-04  1.6250887e+00  8.2437587e-01]
 [-3.4705636e-01 -1.3880417e-01 -3.9192247e-01 -3.4893197e-01]
 [-9.7732508e-01 -1.1207360e+00  3.9429680e-01  3.0471951e-01]
 [ 1.2618488e+00 -8.0525321e-01  1.0977620e-01  2.5427932e-01]]


[[0.5423329  0.6420171  0.30887055 0.12708855]
 [0.1483568  0.5033679  0.14894843 0.65523314]
 [0.3909409  0.07490098 0.95210063 0.6212888 ]
 [0.6808349  0.3143791  0.77111554 0.6649902 ]]




In [26]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.1406015   0.4629479   0.565552   -0.09077167]
 [ 0.25751182 -0.40589654 -0.30747104 -1.3325586 ]
 [-0.3924543  -0.8336538  -1.2177292   0.34940615]
 [-1.0271875   1.9336381   0.4887662  -0.49579418]]


[[0.4761927  0.09755754 0.88546073 0.71390986]
 [0.15597439 0.12334538 0.34041965 0.682994  ]
 [0.9582666  0.10987556 0.7718229  0.11084652]
 [0.45707107 0.21951139 0.08365393 0.45694244]]




In [28]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b = tf.constant([ [10], [100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a,b)

In [33]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [34]:
result.eval()

array([[210],
       [430]], dtype=int32)